
export const AR = {
  dashboard: "لوحة التحكم",
  reception: "الاستقبال",
  patients: "المرضى",
  lab: "المعمل",
  billing: "الفواتير",
  employees: "الموظفين",
  payroll: "الرواتب",
  inventory: "المخازن",
  finance: "المالية",
  setup: "الإعدادات",
  users: "إدارة الحسابات",
  logout: "تسجيل الخروج",
  save: "حفظ",
  cancel: "إلغاء",
  add: "إضافة",
  edit: "تعديل",
  delete: "حذف",
  search: "بحث",
  print: "طباعة",
  export: "تصدير",
  name: "الاسم",
  phone: "رقم الهاتف",
  nationalId: "الرقم القومي",
  bloodType: "فصيلة الدم",
  funding: "جهة التعاقد",
  emergency: "اتصال الطوارئ",
  sessions: "جلسات الغسيل",
  newPatient: "مريض جديد",
  totalAmount: "الإجمالي",
  status: "الحالة",
  date: "التاريخ",
  room: "الغرفة",
  paid: "مدفوع",
  deferred: "آجل",
  free: "مجاني",
  quantity: "الكمية",
  unit: "الوحدة",
  store: "المخزن",
  product: "الصنف",
  transfer: "تحويل",
  mainStore: "المخزن الرئيسي",
  salary: "الراتب",
  bankAccount: "الحساب البنكي",
  shiftPrice: "سعر الشفت",
  shifts: "الشفتات",
  income: "إيراد",
  expense: "مصروف",
  balance: "الرصيد",
  auditLog: "سجل العمليات",
  notifications: "التنبيهات",
  validationPhone: "يجب أن يبدأ بـ 01 ويتكون من 11 رقم",
  confirmation: "هل أنت متأكد؟",
  welcome: "مرحباً بك في نظام إدارة وحدة الكلى",
  services: "الخدمات",
  stores: "إدارة المخازن",
  products: "الأصناف",
  cashAndBank: "الخزينة والبنك",
  reports: "التقارير",
  resetData: "تصفير البيانات",
  preparePayroll: "تجهيز المرتبات",
  archive: "الأرشفة",
  mainCash: "الخزينة الرئيسية",
  subCash: "عهدة الموظف",
  uploadData: "رفع البيانات",
  downloadTemplate: "تحميل النموذج",
  username: "اسم المستخدم",
  role: "الصلاحية",
  password: "كلمة المرور",
  newUser: "حساب جديد",
  permissions: "الصلاحيات الممنوحة",
  checkIn: "تسجيل دخول",
  waiting: "انتظار",
  inSession: "في الجلسة",
  completed: "مكتمل",
  weightBefore: "الوزن قبل",
  bp: "ضغط الدم",
  testName: "اسم التحليل",
  result: "النتيجة",
  normalRange: "المعدل الطبيعي"
};

export const BLOOD_TYPES = ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'];
export const ROOMS = ['A1', 'A2', 'B1', 'B2', 'ICU-1', 'ICU-2'];

export const PERMISSIONS_MAP: Record<string, string> = {
  VIEW_DASHBOARD: "مشاهدة لوحة التحكم",
  MANAGE_RECEPTION: "إدارة الاستقبال",
  MANAGE_PATIENTS: "إدارة المرضى",
  MANAGE_LAB: "إدارة المعمل",
  MANAGE_BILLING: "إدارة الفواتير",
  MANAGE_PAYROLL: "إدارة الموظفين والرواتب",
  MANAGE_INVENTORY: "إدارة المخازن",
  MANAGE_FINANCE: "إدارة الحسابات والمالية",
  MANAGE_USERS: "إدارة حسابات النظام",
  SYSTEM_SETUP: "إعدادات النظام"
};
